services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "32765:80"
      - "32766:443"
    volumes:
      - ./nginx-proxy-prod.conf:/etc/nginx/nginx.conf:ro
      - C:/certs:/etc/nginx/ssl:ro
      - C:\certbot\www:/var/www/certbot:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - C:\etc\letsencrypt:/etc/letsencrypt
      - C:\certbot\www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email ${ADMIN_EMAIL} -d ${DOMAIN_NAME} --agree-tos --no-eff-email
    networks:
      - app-network

 
