services:
  nginx:
    image: nginx:alpine
    ports:
      - "32765:8080"
      - "32766:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - C:/certs:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./SuzumesDeepDungeon/DeepDungeonClient
    networks:
      - app-network

  backend:
    build:
      context: ./SuzumesDeepDungeon
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Key=${JWT_KEY}
      - rawgAPI=${RAWG_API_KEY}
    volumes:
      - db_data:/app/data
      - logs:/app/logs
    networks:
      - app-network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker_data\db
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker_data\logs

networks:
  app-network:
    driver: bridge