services:
  nginx:
    image: nginx:alpine
    ports:
      - "32765:80"
      - "32766:443"
    volumes:
      - ./nginx-proxy-dev.conf:/etc/nginx/nginx.conf:ro
      - C:/certs:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network