services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "32765:80"
      - "32766:443"
    volumes:
      - ./nginx-proxy-prod.conf:/etc/nginx/nginx.conf:ro
      - C:/certs:/etc/nginx/ssl:ro
      - C:\certbot\www:/var/www/certbot:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

 
