version: '3.8'

services:
  frontend:
    build:
      context: SuzumesDeepDungeon/DeepDungeonClient
      dockerfile: Dockerfile.prod
    ports:
      - "80:8080"
    networks:
      - app-network

  backend:
    build:
      context: SuzumesDeepDungeon
    ports:
      - "5000:8080"
    volumes:
      - db_data:/app/data
      - logs:/app/logs
      - certs:/app/certs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Kestrel__Certificates__Default__Path=/app/certs/aspnetcert.pfx
      - Kestrel__Certificates__Default__Password=123f7d_s12SAD_d_fd144f1
    networks:
      - app-network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker_data\db
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker_data\logs
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\certs

networks:
  app-network:
    driver: bridge
