name: Production Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create data directories
      run: |
        # Создаем директории для данных и сертификатов
        New-Item -ItemType Directory -Force -Path C:\docker_data\db
        New-Item -ItemType Directory -Force -Path C:\docker_data\logs
        New-Item -ItemType Directory -Force -Path C:\certs
        
        # Устанавливаем права доступа
        icacls "C:\docker_data" /grant "Everyone:(OI)(CI)F" /T
        icacls "C:\certs" /grant "Everyone:(OI)(CI)F" /T

    - name: Copy certificate (if not exists)
      run: |
        # Копируем сертификат из репозитория (если он там есть)
        if (Test-Path -Path "certs\aspnetcert.pfx") {
            Copy-Item -Path "certs\aspnetcert.pfx" -Destination "C:\certs\" -Force
        }
        else {
            Write-Host "Certificate not found in repo, using existing on server"
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - name: Build Angular app
      working-directory: SuzumesDeepDungeon/DeepDungeonClient
      run: |
        npm ci
        npm run build -- --configuration production

    - name: Build ASP.NET app
      working-directory: SuzumesDeepDungeon
      run: dotnet publish -c Release -o ./publish

    - name: Deploy with Docker Compose
      run: |
        docker compose -f docker-compose.prod.yml down
        docker compose -f docker-compose.prod.yml build --no-cache
        docker compose -f docker-compose.prod.yml up -d
        
    - name: Apply database migrations
      run: docker exec backend dotnet SuzumesDeepDungeon.dll --migrate
