name: Production Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        choco --version

    - name: Install Node.js 20 via Chocolatey
      run: |
        choco install nodejs-lts --version=20.19.0 -y
        refreshenv
        node --version
        npm --version

    - name: Create data directories
      run: |
        New-Item -ItemType Directory -Force -Path C:\docker_data\db
        New-Item -ItemType Directory -Force -Path C:\docker_data\logs
        New-Item -ItemType Directory -Force -Path C:\certs

    - name: Copy certificate
      run: |
        # Проверяем наличие сертификата в репозитории
        if (Test-Path -Path "certs\aspnetcert.pfx") {
            Copy-Item -Path "certs\aspnetcert.pfx" -Destination "C:\certs\" -Force
            Write-Host "Certificate copied from repository"
        }
        else {
            Write-Host "Using existing certificate on server"
        }

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build Angular app
      working-directory: SuzumesDeepDungeon/DeepDungeonClient
      run: |
        # Используем установленную версию npm
        npm ci
        npm run build -- --configuration production

    - name: Build ASP.NET app
      working-directory: SuzumesDeepDungeon
      run: dotnet publish -c Release -o ./publish

    - name: Deploy with Docker Compose
      run: |
        docker compose -f docker-compose.prod.yml down
        docker compose -f docker-compose.prod.yml build --no-cache
        docker compose -f docker-compose.prod.yml up -d
        
    - name: Apply database migrations
      run: docker exec backend dotnet SuzumesDeepDungeon.dll --migrate
      
    - name: Verify deployment
      run: |
        Start-Sleep -Seconds 15
        curl http://localhost:5000/api/health
